---
- hosts: guests:extras
#- hosts: extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
    # ruby
    - command: /home/isucon/.xbuild/ruby-install 2.3.0 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
    - command: /.local/ruby/bin/gem install bundler
      args:
        creates: /home/isucon/.local/ruby/bin/bundle
    # node
    - command: /home/isucon/.xbuild/node-install v4.4.3 /home/isucon/.local/node
      args:
        creates: /home/isucon/.local/node/bin/node
    # golang
    - command: /home/isucon/.xbuild/go-install 1.6.2 /home/isucon/.local/go
      args:
        creates: /home/isucon/.local/go/bin/go

- hosts: guests:extras
  become: yes
  gather_facts: no
  tasks:
    - name: Apt add Dotdeb jessie repository
      apt_repository: repo="{{item}}"
      with_items:
          - deb http://packages.dotdeb.org jessie all
          - deb-src http://packages.dotdeb.org jessie all
      tags: php7
    - name: Apt install Dotdeb key
      apt_key: url=http://www.dotdeb.org/dotdeb.gpg
      tags: php7
    - name: Apt update
      apt: update_cache=yes
      tags: php7
    - name: PHP7 install
      apt: name="{{item}}"
      with_items:
        - php7.0-cli
        - php7.0-fpm
        - php7.0-mysql
        - php7.0-memcached
      tags: php7
    - name: copy www.conf (php-fpm)
      copy: src=../files/etc/php/7.0/fpm/pool.d/www.conf dest=/etc/php/7.0/fpm/pool.d/www.conf owner=root mode=644
    - name: stop php-fpm
      service: name=php7.0-fpm state=stopped enabled=yes
